### PR TITLE
Add Linux backend

### LINKED ISSUE #7: Linux support
Hello!

This plugin sounds amazing. I've read that Linux is not supported. Unfortunately, I can't contribute with a PR because I don't know how to Vimscript... however, I've dug the docs and code for what your plugin might listen to and what the corresponding Linux counterparts are.

On most modern Linux systems, `/sys` is a kernel-backed filesystem where device information can be queried. As per the Unix philosophy, these directories also contain just plain old text files.

The AC power brick is available here: `/sys/class/power_supply/AC` (these directories are all symlinks to "magic" device-ID based locations, such as `../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/AC`...)

```bash
$ cat /sys/class/power_supply/AC/type
Mains
$ cat /sys/class/power_supply/AC/online
1
```

The battery, or batteries, are available under `/sys/class/power_supply/BAT0`, `BAT1`, ...

```bash
$ cat /sys/class/power_supply/BAT0/type
Battery
$ cat /sys/class/power_supply/BAT0/present
1
$ cat /sys/class/power_supply/BAT0/technology
Li-ion
$ cat /sys/class/power_supply/BAT0/alarm
0
$ cat /sys/class/power_supply/BAT0/capacity
95
$ cat /sys/class/power_supply/BAT0/capacity_level
Normal
$ cat /sys/class/power_supply/BAT0/charge_full
4294000
$ cat /sys/class/power_supply/BAT0/charge_full_design
4294000
$ cat /sys/class/power_supply/BAT0/charge_now
4113000
```

I believe the last 3 values are in mA. Unfortunately, some batteries (or ACPI implementations?) might report `energy_full`, `energy_now` and `energy_full_design` instead of `charge_*`, which will be measured in either mWh or Wh.
But I believe simply hooking onto the `capacity` value (expressed as %) should be fine as a presentation to the user. As far as I can see, the graphical widget in KDE does the same.

These value need not be manually updated by a service or a system call. The kernel keeps the value up-to-date, and simply reading the appropriate "system file" gives you the value.

### PR DESCRIPTION
**Pull request by lambdalisue**
SSIA

Close #7

### CODE REVIEW

**Comment by whisperity** [comment]
Something is not okay with [vim-airline](https://github.com/vim-airline/vim-airline)'s plugin regarding this plugin. (This is how I got to know about this plugin's existence, seeing the updated files when I updated Airline.)

Generally, it seems to work for me. However, on certain platforms, the AC adapter might be in the `ACAD` directory ("AC adapter", instead of simply `AC`), and batteries might be `BAT1`, `BAT2`, etc.

So in general, I believe to support other platforms where different IDs might be assigned, the value should be got from a glob expression `AC*` and `BAT*`. I hope Vim can support reading from such files, or simply otherwise iterating directory names.

**Comment by lambdalisue** [comment]
@whisperity Sorry for late. Could you try the latest one on this PR?

**Review by whisperity — APPROVED** [review]
I think this works fine, thank you!

Screenshot_20201005_125604

**Comment by whisperity** [comment]
You should update the documentation file too!

https://github.com/lambdalisue/battery.vim/blob/6c3739ac53679b1ed0ef9ce569c4e29499b50c3f/doc/battery.txt#L26

https://github.com/lambdalisue/battery.vim/blob/6c3739ac53679b1ed0ef9ce569c4e29499b50c3f/doc/battery.txt#L143

(Also, there is a typo here: https://github.com/lambdalisue/battery.vim/blob/6c3739ac53679b1ed0ef9ce569c4e29499b50c3f/doc/battery.txt#L93 `battry` instead of `battery`.)

**Comment by lambdalisue** [comment]
Merged. Thanks for your support @whisperity 👍

**Comment by iAmG-r00t** [comment]
Hey @whisperity Kindly assist on this issue #10 if you can, would really appreciate.

/gr00t

**Pull request merged**
